### ISSUE TITLE
Distinguishing between types of georesolution

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#261]
One issue that we're encountering with the Pausanias text is that it's so full of spatial content, which is not necessarily to do with place. So-called "proxies" for places include peoples, physical features (lacking toponymns), human constructions (temples, images, institutions). Now, we'd like to georesolve these as far as possible - and we can, by reading the text and surmising which places these proxies signify. However, since they aren't strictly "places", it would also be useful to differentiate these other types of location signifiers from places when visualised.

**Comment by rsimon** [comment]
Should be a prime use case for tags I think? You could agree on your own vocabulary, and tag places accordingly.

**Comment by ChiaraPalladino** [comment]
Relations are not the same thing as categories, in terms of dynamics of annotation, if you pass me the expression. 
I'm still unsure about how we can fully exploit the potential of Recogito to properly mark relations, which occur between two entities. On the other hand, categories ("temple", "mountain", "river") can be explicitly indicated in the text itself, in which case I think it's important to mark the phenomenon somehow, or can be explicited by the annotator, who may or may not know them directly from the text or the historical period to which it belongs or any other evidence available. We should bear in mind that ancient categories are different from ours as well: I may want to mark a place as a river because I know that there was one there, but that doesn't mean necessarily that the text I am annotating indicates that place as a river (it may have been known as a sea, for example). 
If relations are hard in technical terms, place categories are difficult for semantic reasons. Again, a good topic to discuss together with more scholars.

**Comment by rsimon** [comment]
Just pinging @eltonteb - do you think the tagging feature (now available - although not yet with a nice drop-down to re-use existing tags) works as a solution for distinguishing types of geo-resolution?

As far as relations between annotations are concerned: +1 for discussing this on the Commons forum! (In fact there's also [this thread](http://commons.pelagios.org/groups/recogito-users/forum/topic/connected-annotations-and-multiple-possibilities/) where some discussion was initiated a while ago.) Also, I'd like to create a dedicated GitHub issue for this.

**Comment by eltonteb** [comment]
as you see, I'm working on it :). If you'd like, I could share the document with you that I've started working on? I'd like to make my annotation method more robust, so it would be useful to have your feedback. Let me know.

**Comment by rsimon** [comment]
Yes - do share. (Although if it's Pausanias, I think you already shared that with me? In any case: best send me the URL - or post here, if it's a public doc.)

**Comment by ChiaraPalladino** [comment]
Yes please, do share! :)

**Comment by rsimon** [comment]
Pinging @eltonteb again, as the discussion on relating annotations with each over is now covered in the separate issue #299 ("using tags to associate annotations"). Can we otherwise close this issue? I'm noting that dropdown suggestion for tagging is now also covered in a separate issue: #296 ("Tags - automatic completion).

**Comment by rsimon** [comment]
@eltonteb I think the discussion is now moving forward in #299 ("using tags to associate annotations"). If it's OK, I'd close this issue.
