### ISSUE TITLE
"Pseudo-forking" via backup & restore

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#281]
Personal restore now works, but the restore process will retain original IDs for document parts and annotations - which means that DB metadata import will reject; while ES import would generate duplicates.

Extend the restore process, so that in case an existing document is restored elsewhere, new IDs for document, parts and annotations are generated, and all references are properly re-wired.

**Comment by efi** [comment]
Hmmm...

I would like to advice some caution. For now it seems like I cannot remove annotations from a re-uploaded document:

http://recogito.pelagios.org/document/recogito2rocks/part/1/edit (cool URL, isn't it? :D)

**Comment by rsimon** [comment]
Well, you hacked the document ID (on which all other things depend) creating an inconsistency in the system.  That's the reason issue #250 exists, and that's the point about this issue in the first place.

**Comment by rsimon** [comment]
Can you just detail the steps you hacked? Only the ID in the metadata.json?

**Comment by rsimon** [comment]
Hm - checked again now, and in fact there shouldn't even be an inconsistency. Arguably, you've used a "hacky" way of getting the doc into Recogito. But generally there should be nothing wrong with it. Technically valid (although I should probably conduct some sort of validity chek on the ID).

**Comment by efi** [comment]
Yeah, that's somehow the point: The "Pseudo-Forking" kind of mixes two concerns. A Backup should re-create exactly the same thing (so #250 is important, I think) in an atomic all-or-nothing-process that definitely should also create the former ID (since this is externalized as part of the URL).

On the other hand an internal fork should avoid any resemblance with the original on a metadata level and instead only "accidentially" have the same content (again: the content should appear to be the same but should of course have distinctly different part_ids and stuff)

I just fiddled around with the files in the metadata.json. But even after I provided a (valid) reduced annotations list, the old annotations still seem to have survived my previous deletion. That kind of inconsistencies must be avoided since they do not show as errors or are transparent to your business logic.

Hope you don't mind the hacking, but I think it's better now and better me than soemone else later...  so far everything also survived my `<script>alert("hello")</script>` metadata entries... ;-)

**Comment by rsimon** [comment]
No, the hacking is fine :-) I could definitely reproduce this. The strategy, as I planned it, was that the restore would reproduce everything exactly as before, with the same IDs as you say. As soon as the ID has changed or is no longer available, all the IDs *should* be completely re-wired.

I think it still makes sense as a protection for the case when someone pulls a backup, and later wants to restore but because of a 1:whatever chance, the ID has be re-taken in the mean time.

**Comment by rsimon** [comment]
Anyways: I need to investigate this further. The error is definitely not true for re-uploaded documents in general, only those where the ID was tempered with. I'll look into it. But I'm off to a meeting in 10min, so will be next week. (Remember: *friendly* hackers don't hack live system on Friday afternoons ;-) )

**Comment by rsimon** [comment]
P.S.: ah - I see the inconsistency leak now & it's actually fixable pretty easily (and should not have happend in the first place). Might still get that done later depending on when I can get out of the meeting. So thanks for pointing this out :-)

**Comment by efi** [comment]
Yeah, seems that I overstressed the temporal aspect of the line "But feel free to explore Recogito already now, *while it's under development*." :D

Switched my doc to private now anyway. Have a nice weekend!

PS: My fake ID should actually even be valid: 14-digit alphanumeric lower-case string

PPS: 1:whatever would then actually be a total_document_count:6140942214464815497216 chance of an accidential duplicate...

**Comment by rsimon** [comment]
Hm, I take your point, maybe it's cleaner to take the chance, and avoid the rewiring in the upload...

**Comment by rsimon** [comment]
I made some... refinements... now. But I agree that this should fully reproduce the original backup, with all IDs unchanged. Also, I'll give higher prio to issue #250, so backups are signed as a protection against hacking the contents.

**Comment by rsimon** [comment]
Ah - wait. Didn't work just yet...

**Comment by rsimon** [comment]
P.S.: the loophole should now be closed. It's still possible to hack the ID, but no "free-floating" annotations will occur.

**Comment by rsimon** [comment]
Note: document restore from the personal profile page now checks for backup signature - see issue #250.
