### ISSUE TITLE
flagging

### ISSUE THREAD

**Issue by eltonteb** [pelagios/recogito2#293]
When annotating a feature as a place, which I know won't have a gazetteer reference, can there be a shortcut to flagging it, rather than having first go through the process of searching for its location?

**Comment by rsimon** [comment]
I'm slightly against adding additional buttons (remembering that unintelligible long row of tiny icons on the Recogito v.1 frontpage...) But, along the lines of a power-user feature, a keyboard shortcut perhaps?

Alternatively and/or additionally: the "card" shown for places that could not be resolved to an automatic match at all currently has only two buttons. So a third "flag" button may make sense, given that this card might frequently appear, anyway, when marking a phrase without a suitable gazetteer match? Beyond three buttons in a group, I'd be worried about usability implications.

![image](https://cloud.githubusercontent.com/assets/470971/19958506/1c8827aa-a1a0-11e6-83a8-4713f8840ab8.png)

**Comment by eltonteb** [comment]
absolutely. That long list we had before was redundant. I was merely thinking of a shortcut to get to the amber flag.

on Leif's point - about seeing the locations of the places in the surrounding text already annotated (as one could do in Recogito 1): could this be seen in the mapview pop up?

**Comment by rsimon** [comment]
Good point about "surrounding" places. The way things are implemented now, it's technically a bit tricky. But implementation details need to change, anyway, in order to fix a related issue (left/right arrow keys failing on certain constellations). Once that's done, adding, e.g. extra small dots (two before, two after) would be a nice addition. Do you want to create an extra issue for this?
