### ISSUE TITLE
JSON and GeoJSON exports

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#305]
I have a question on how the JSON exports are right now. It seems to me that both JSON and GeoJSON only catch a part of the data that result from georeferencing. To be clear, the csv format seems paradoxically more useful because it keeps additional data resulting from Pleiades references, for example (including place category, just to mention one). This was extremely useful for my research. On the other hand, JSON gives the possibility of representing spatial entities as polygons fairly quickly, but with no additional data to the places referenced. 

Is this the "final" format for this export?

**Comment by rsimon** [comment]
Hi Chiara, no - it's basically a "demo format" right now, waiting for someone to make use of it, and provide input on what they'd like to see in the data :-) (CSV is simply more advanced because there was already someone asking for a few specific enhancements.)

From a quick look, the GeoJSON now only includes bare minium info from the gazetteers - geometry and labels. I may have some time in between tomorrow, to look into extending it. Not 100% sure about the format yet, but I'll at least add in the obvious things: annotation quotes, gazetteer URIs, tags, comments. Does this sound good to get started?

Also: do you prefer to have the GeoJSON (i.e. places) over the JSON-LD (annotations)? Or should I start with JSON-LD instead?

**Comment by ChiaraPalladino** [comment]
I can deal with both, but GeoJSON is certainly more useful for my particular purpose, so if I may make a request that would be the first one :) 

I am doing some experiment on CartoDB to see how regions and other spatial extensions interact with places represented as points, and how categories of places can be retrieved from databases based on what we currently have. So, judging from what I see in Pleiades, at least to have the Place type and the tags (I mean, the tags added on Recogito in the annotation process) is crucial. It would be also great to be able to see the temporal attestations (https://pleiades.stoa.org/places/59849/indoi), which I noticed is part of the new format in Pleiades, but may be tricky to include in the export format.

**Comment by efi** [comment]
Well, taking the risk of bein the annoying kid jabbering when two grown-ups want to have a conversation... ;-)

I just want to say that having both JSON-LD and GeoJSON at the same time is a really nice thing for a geographically focused project in an LOD environment. I just recently came across https://github.com/sfsheath/roman-amphitheaters and like how they did it for their data: https://raw.githubusercontent.com/sfsheath/roman-amphitheaters/master/roman-amphitheaters.geojson

**Comment by rsimon** [comment]
Ah good point about creating GeoJSON that is also JSON-LD compliant. I'd appreciate a bit of sanity checking & help. If you can draft up a template of what that should look like - do post it here!

Another issue, of course, is the difference between the Open Annotation JSON-LD and the GeoJSON-LD. There will be no way around publishing those as two different exports, as they represent different views on the sam thing (place-centric view vs. document-centric). But it's not a problem to produce both, of course.

**Comment by rsimon** [comment]
@ChiaraPalladino I added some additional information to the GeoJSON downloads. Every feature now includes:

- place title, as recorded in the gazetteer
- gazetteer URIs for the place, as used in the annotations
- place types, as recorded in those gazetteer records that the annotations link to
- source gazetteers of the URIs the annotations link to
- quotes from the annotations (i.e. the text highlighted by the annotations)
- tags from the annotations
- comments from the annotations

**Comment by rsimon** [comment]
I should add: it's a bit of a quick hack (I'm in a pub right now...) Let me know if it works. The basic plumbing is in place now, though & we can easily tweak details and format.

**Comment by ChiaraPalladino** [comment]
I finally found the time to have an accurate look at this. Two things are ambiguous to me: 

1) The place titles as recorded in the gazetteer uris, I'm not sure where they come from. A good example is Naxos: the GeoJSON from Recogito looks like this: 

{
    "type" : "Feature",
    "geometry" : {
      "type" : "Point",
      "coordinates" : [ 25.49, 37.05 ]
    },
    "properties" : {
      "titles" : "Naxos (island), Naxos Ins., Naxos",
      "annotations" : 3
    },
    "uris" : [ "http://pleiades.stoa.org/places/599822" ],
    "titles" : [ "Naxos (island)" ],
    "source_gazetteers" : [ "Pleiades" ],
    "quotes" : [ "Κυκλάδων κρατίστη", "Νάξος", "μικρὰ λέγεται Σικελία" ],
    "comments" : [ "alternative name for Naxos" ]
  }

So "titles" should store the alternative names among the properties, but in the Pleiades link you find this: 
![image](https://cloud.githubusercontent.com/assets/15249889/21611737/5fe876fe-d1ce-11e6-9fd7-94443f6eb144.png)

2) Same for the place type. I am not sure where it comes from but it takes, I suspect, the feature type in Pleiades, instead of the place type. 
Place type is here: 
![image](https://cloud.githubusercontent.com/assets/15249889/21613198/89213d52-d1d4-11e6-8f13-6581ad4fe93a.png)

Feature type in Pleiades is here (I'm copying the JSON data): 
{
    "features": [
        {
            "geometry": {
                "type": "Point",
                "coordinates": [
                    25.49,
                    37.05
                ]
            },
            "type": "Feature",
            "id": "location-of-naxos-ins",
            "properties": {
               ...
            }
        }
    ]

The rest is great and the quotes from the annotations are genius.

**Comment by ChiaraPalladino** [comment]
Also, I wish there was a good way to represent the temporal attestations as well, e.g. https://pleiades.stoa.org/places/599822/naxios  

![image](https://cloud.githubusercontent.com/assets/15249889/21613514/d4d69296-d1d5-11e6-980f-7e50fc97f879.png)

But this requires some effort because Pleiades has different ways of giving this information.

**Comment by rsimon** [comment]
Hi @ChiaraPalladino,

to your first question:

> The place titles as recorded in the gazetteer uris, I'm not sure where they come from.

Yes, I guess we short sort this out a bit more. The titles listed in the properties come from __all__ the gazetteers in the system. In the case of Naxos, the properties list the titles from Pleiades as well as those from DARE. The annotation, however, links to Pleiades, so the other fields are sourced __only__ from Pleiades. I agree we should stay consistent here, and - in this case - use only info from Pleiades since this what the annotation links to.

Should we also include the names from the gazetteers? At present, only the title/headword is included in the GeoJSON. The headword will usually re-appear as a name. But there are (obviously) usually more names in the gazetteer data, than just the headword. (To clarify: it's really just the GeoJSON export that's affected. Internally, we do of course keep all the names. See e.g. for Naxos:

![image](https://cloud.githubusercontent.com/assets/470971/22027531/708176a8-dcd4-11e6-8854-d4e1f4f96afa.png)

The place types don't currently seem to come through at all (in GeoJSON as well as CSV). I'll need to look into that.

**Comment by rsimon** [comment]
With regard to time: yes I agree. It may take a bit longer to get this into Recogito. But we have definitely scheduled time to work on the issue as such as part of the upcoming revision of Peripleo - which I'm about to start. (And Peripleo 2.0 will share the whole gazetteer infrastructure with Recogito 2.0.)

**Comment by ChiaraPalladino** [comment]
Great, thanks for the explanation.

> Should we also include the names from the gazetteers?

I would say yes. It's an important information. I would store it in another property, other than "titles", something like "alternative names".

**Comment by rsimon** [comment]
I just pushed a small update:

- in the GeoJSON properties, `titles` now only includes the titles from gazetteer records actually referenced by the annotation
- at the top level, there's now an additional `names` field listing the names from the gazetteer records referenced by the annotation

**Comment by rsimon** [comment]
The reason the place types are not showing up was due to a small bug in the gazetteer import. I fixed the bug, but will need to re-import Pleiades so that the place types get properly picked up. (Will probably do that tomorrow.)

**Comment by ChiaraPalladino** [comment]
Thanks Rainer :D 
I'll take some time to see how it works now, will get back at you soon!
