### ISSUE TITLE
Default user created with plaintext E-Mail irrespective of encryption setting

### ISSUE THREAD

**Issue by dimidd** [pelagios/recogito2#335]
```[error] - application -

! @72cdj32il - Internal server error, for (GET) [/settings/account] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)```

**Comment by rsimon** [comment]
Hm. On logout, there's not really anything happening except for the session cookie being erased. According to the log output, this seems to happen when accessing your personal account details edit form. The form will also display the E-Mail address that's stored in the system with your user. That E-Mail address is normally encrypted; and from the log output it seems that something goes wrong with the decryption. 

Two quick questions:
- in your installation of Recogito, did you set an E-Mail encryption key? Note that the default setup does come with a (dummy) key, so unless you commented that out, you probably have one.
- can you look into your user database record and check what the content of the E-Mail field is?

Thx,
Rainer

**Comment by dimidd** [comment]
recogito.email.key = "my secret key"

email: recogito@example.com

After restarting recogito I'm unable to reproduce the error, weird.

2016-12-14 18:30 GMT+02:00 Rainer Simon <notifications@github.com>:

**Comment by rsimon** [comment]
Ah - I see what's the problem now. Yes, good catch.. and bug on my part. You do have the default dummy encryption key set, which means Recogito expects E-Mails to be encrypted. However, since you run your own, clean setup, the schema definition will create a hard-wired default "recogito" user, with an unecrypted password. (I'm strongly assuming the problem does __only__ happen with that default inital user, right?)

For a quick fix: create a new user through the UI. That won't have any problems. Then, delete the default Recogito user & you should be fine. However, I'll also change the way the default user gets created, so that it comes with a proper en- ur unencrypted password, depending on system settings.

**Comment by rsimon** [comment]
I just changed the title of the issue, so that I have the "root cause" visible in my ticket list. Hope that's ok.
