### ISSUE TITLE
Re-Apply and variant spellings

### ISSUE THREAD

**Issue by paulbroyles** [pelagios/recogito2#343]
The Re-Apply function causes problems when names have alternate spellings in the document. I'm annotating a text that includes the toponym "Hampton." Sometimes it is spelled with a terminal e. If I annotate it for the first time where it is spelled "Hampton," and allow Recogito to Re-Apply, it applies the same annotation to all instances of "**Hampton**e"--except that the final e is not included. To correctly highlight "Hamptone" I must individually delete the automatically applied annotation from each instance and apply a new annotation. Obviously Recogito can't be expected to handle variant spellings on its own, but it would be good to be able to restrict it to reapply annotations only to whole words (delineated by whitespace or punctuation marks).

**Comment by rsimon** [comment]
Hi Paul,

yes, I agree, the re-apply function needs some more work. (I'm also linking in issue #272, which is related.) In the first version of Recogito we did actually require surrounding whitespace or punctuation, but then had a few cases of languages where this was explicitely not desired (Hebrew).

In any case: the re-apply function definitely needs (and will) get smarter, in order to avoid those cases you are describing.

**Comment by rsimon** [comment]
Since this is language dependend, perhaps we should make it a setting in the __Annotation preferences__...
