### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#347]
I've had a closer look at all of the export formats. CSV already looks good but there are some core features that were in Recogito 1 and I think should be kept here as well: 

Tags and comments 
Place type as recorded in the gazetteer (see also https://github.com/pelagios/recogito2/issues/305)
Possibly the temporal span as recorded in the gazetteer 

it will certainly make sense at some point to implement the other export options too (I'm thinking about JSON-LD especially) but I am not sure what we would need for them. 

#305

**Comment by rsimon** [comment]
I just added gazetteer place types, tags and comments. Obviously, the problem is that an annotation can have multiple, while CSV only provides one field to stuff them all in. Not sure about a perfect solution for this (if there is one). But as a workaround, I separated multiple values using a | character.

I agree about the temporal spans. That's definitely planned; and the model has room for them. But we currently not picking up Pleiades time URIs (nor anyone else's) - yet.

**Comment by rsimon** [comment]
P.S.: for tags and comments, only the __values__ show up in the CSV, not the creator metadata (who and when). It's recorded internally, of course, but probably something we'd need to reserve for the more structured output formats (JSON-LD etc.)
