### ISSUE TITLE
Cant import TEI documents (!?)

### ISSUE THREAD

**Issue by lb42** [pelagios/recogito2#404]
I tried to upload a basic TEI document  and was a bit shocked to receive the message attached. Isn't enrichment of basic encoded texts one of the prime use cases for this lovely tool? 
![recogito](https://user-images.githubusercontent.com/660724/27984130-55c1b184-63c5-11e7-98f8-d126d2471732.png)

**Comment by rsimon** [comment]
As the upload dialog says, TEI is, unfortunately not among the the supported upload formats. You can find additional info on the formats in the [FAQ](http://recogito.pelagios.org/help/faq).

However we are going to implement TEI support later this year (also listed in the FAQ I think). I will start this in October.

**Comment by rsimon** [comment]
PS: if you care to help and/or make this happen earlier: there is a proof-of-concept for this (the basis for the October work) in this branch:

https://github.com/pelagios/recogito2/tree/tei-trial

It uses CETEIcean under the hood.
---
Sent via mobile

**Comment by lb42** [comment]
Thanks for the quick response and apologies for not reading the faq more carefully! Id be glad to help with the dev if I can.

Sent from my Huawei Mobile

-------- Original Message --------
Subject: Re: [pelagios/recogito2] Cant import TEI documents (!?) (#404)
From: Rainer Simon
To: pelagios/recogito2
CC: Lou Burnard ,Author


PS: if you care to help and/or make this happen earlier: there is a proof-of-concept for this (the basis for the October work) in this branch:

https://github.com/pelagios/recogito2/tree/tei-trial

It uses CETEIcean under the hood.

Sent via mobile

**Comment by rsimon** [comment]
That's great! It will be a while until I'll have the time to look into this properly. But *if* you want to look into (parts of) the issue ahead of time: 

- The main issue - rendering TEI in Recogito's annotation view - should be fully covered by [CTEIcean](https://github.com/TEIC/CETEIcean). The prototype in the tei-trial branch includes a rough integration that basically works, just lacks some proper CSS styling.

- There's lots of plumbing in between that needs to finished, which will be tricky for anyone not familiar with the Recogito codebase (but otherwise not rocket science). So probably best left to me. It's not the most exciting work, anyway ;-)

- The missing part at the moment (which I haven't looked into yet) is the translation of the "annotation anchors", i.e. the data structure used to define where the annotation starts (and ends) in the text. The current prototype handles TEI just as if it were plaintext: for each annotation, it records the character offset (e.g. "starts at the 127th character in the rendered HTML") and then uses that to render the highlight via JavaScript. Obviously, what's needed instead is a proper translation of selection ranges to am XPointer expression. I think the people behind CETEIcean (@hcayless, @raffazizzi) may have implemented this already at some point. But I admit I haven't checked back with them for a while.

**Comment by rsimon** [comment]
Quick update: 
* Basic CETEIcean integration is now in the master branch
* Parts of the plumbing that's required to import TEI into the workspace is done, too. But it's currently disabled in the master branch. (I.e. the official server at [recogito.pelagios.org](http://recogito.pelagios.org) will still reject TEI files.) To test the feature locally, just uncomment [this line in the code that handles the upload content types](https://github.com/pelagios/recogito2/blob/master/app/models/ContentType.scala#L79).
* Translating annotation anchors back and forth between XPath (relative to the TEI structure) and the UI DOM also seems to work fine, but there are probably various edge cases that still need fixing.

A significant number of things are still missing & will be added in time with the dev schedule (i.e. release November):
* When importing a TEI, existing `placeName` and `personName` tags should be stripped out of the XML, and converted to standard Recogito standoff annotations
* When exporting back to TEI, Recogito annotations should be merged back into the original XML structure (where possible), and a valid TEI/XML file should be returned.
* NER is an open issue. I'm not sure StanfordNLP would take XML as an input. If we want to support NER of TEI-encoded material, we may need to figure out a way how we can
  - strip out the plaintext from the XML (easy)
  - run the text through NER (easy)
  - from the NER results, figure out _where_ in the original XML structure the entities were located, and generate the corresponding XPaths (not easy at all...)

If there is an existing solution, this might not be necessary. Otherwise, the complexity might in fact be prohibitive, given our limited resources. But let's cross those bridges when we come to them.

**Comment by rsimon** [comment]
__UPDATE:__ due to limited resources, we won't be able to offer NER during upload for TEI for the time being.

**Comment by rsimon** [comment]
__UPDATE:__

- TEI import closed in #421 
- TEI export in progress in #422
