### ISSUE TITLE
Image popup position

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito2#406]
Finally time to think up a proper solution for the image popup. Typical case is where the image popup is neatly placed into the viewport at first. But then, when it grows during annotation (e.g. because a place mapping is added), it starts to exceed the screen space. Most of the time, this also pushes out the OK/Cancel buttons which is particularly annoying. We need to change somehow.

Possible apporach: make the popup "pseudo-scrollable", i.e. when scrolling (mousewheel), move the map upwards (thus pulling the popup along), without re-invoking the auto-placement trigger.

Question is generally: should the auto-placement triggered at all once the popup is open? (Maybe see if the popup is in focus, or the map?)

**Comment by rsimon** [comment]
Also (sort of) relates to #238.

**Comment by ChiaraPalladino** [comment]
Basically what I do to avoid the problem when it occurs is to shift to the hand pointer (by clicking on the space bar), zooming out so that the popup is visible again, and clicking okay. So I leave the annotation "suspended" for a while while zooming out. 

I also suspect that the autoplacement trigger does not activate when the image is very zoomed in, but I need to verify this assumption with further evidence :)

**Comment by rsimon** [comment]
The map now stays moveable (pan/zoom) during editing, which resolves the issue.
