### ISSUE TITLE
Automatic annotation of identical words

### ISSUE THREAD

**Issue by JWEvidence** [pelagios/recogito2#525]
When you annotate one person (actor) manually and continue with automatically recognizing the same persons in the whole document, Recogito also selects the identical combinations of letters as part of a non-similar word. For example, when you annotate "Mark" as person,  Recogito will automatically annotate as person the parts of words like “questionMARK”, “benchMARKing” etc. Is there a way to automatically annotate the words that are exactly identical to the manual selected one?

**Comment by rsimon** [comment]
Hi,

the way it's currently implemented, matches are case sensitive; but don't require whitespace around them. As an example: if you annotate 'now' in the text, Recogito will generate a match on the word k'now', but not on 'Now' (due to uppercase).

(I agree that ignoring whether there is whitespace or not doesn't make much sense in western languages. But such matches are desirable e.g. in Hebrew - which is in fact the particular case where this feature's behavior originates from.) 

Anyways, the implementation is definitely going to change soon, and probably allow additional config parameters. Please also note that this is already covered in an existing issue: #343.

**Comment by rsimon** [comment]
Closing this as duplicate to #343 (development of which is about to start).
