### ISSUE TITLE
Document imported via IIIF not displaying properly

### ISSUE THREAD

**Issue by mromanello** [pelagios/recogito2#570]
Hi @rsimon 

As I mentioned, I'm running into some issues when importing a manuscript from e-codices (https://www.e-codices.unifr.ch/en/list/one/bge/gr0044) into Recogito (fwiw the document is https://recogito.pelagios.org/document/mtxabgqcgnbxj9/part/1/edit).

The first couple of pages display OK, but the others don't (although when fiddling a bit with zoom levels something eventually shows up). I attach some screenshots.

Hope it helps to track the issue down!

![image](https://user-images.githubusercontent.com/310693/47080539-8b185880-d208-11e8-979e-f9c7c22d75ec.png)

![image](https://user-images.githubusercontent.com/310693/47080571-a2574600-d208-11e8-8388-af01b93b7732.png)

**Comment by rsimon** [comment]
Hi @mromanello,

thanks for this. This is (somewhat of) a know issue, but I now realize there was not yet a ticket for it. There's a bug with the view layer that we've been trying to fix, but haven't yet nailed down. It's definitely related to the computation of the pyramid levels/resolutions from the canvas size reported in the manifest, and happens under (yet to be completely identified...) certain circumstances where (in addition to those circumstances...) the image dimensions are not an exact multiple of the tile size. At least that's my current suspicion.

We've been through a round of discussions about this (but also other related issues) [here](https://github.com/klokantech/iiifviewer/issues/23). But nothing final yet. FWIW, our code where the X/Y/Z values get derived from the image dimensions is here:

https://github.com/pelagios/recogito2/blob/master/app/assets/javascripts/document/annotation/image/iiif/iiifSource.js#L89-L129

Input from anyone who's knowledgeable in the IIIF Image API is greatly, crucially and gratefully appreciated :-) I tried to cross-check with (and port from) the corresponding code bits in OpenSeadragon at some point (see [here](https://github.com/openseadragon/openseadragon/blob/master/src/iiiftilesource.js#L310-L372)), but then ran out of time, since their code is organized a little different.

**Comment by lutzhelm** [comment]
I ran into the same (underlying) issue. Please have a look at my thoughts on that in kitodo/kitodo-presentation#306 and the proposed solution in klokantech/iiifviewer#25.

**Comment by rsimon** [comment]
Hi @regisrob, thanks for this - yes it's the exact same issue. 

@lutzhelm: fantastic, many thanks for letting me know. Indeed this looks like what's happening. I'll try to fix along the same lines.

**Comment by rsimon** [comment]
Dear all, I just ported the fix from @lutzhelm over to Recogito - and it seems to have done the trick perfectly. Many many thanks for this!

**Comment by lutzhelm** [comment]
FYI, my pull request to OpenLayers that introduces a built-in IIIF Image API tile source has just been accepted: openlayers/openlayers#9430
Should you ever consider moving to OpenLayers 6 once it is released, IIIF will already be there...

**Comment by rsimon** [comment]
I saw that - fantastic. Many thanks for this!
