### ISSUE TITLE
Chronology data from Pleiades?

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#592]
Is there any way to make chronology information from Pleiades available in the data export? I do see dates of attestation, for example, when I navigate Peripleo: 

![image](https://user-images.githubusercontent.com/15249889/49043945-6b2a6c00-f19a-11e8-8226-f715e9044c0a.png)

At present I think we get geometry type, alternative names, place_type and coordinates from Pleiades.

**Comment by rsimon** [comment]
"Temporal bounds" is something that gets indexed in Recogito, too. (Although, generally, indexing works a bit different between Recogito and Peripleo.) I'll put that on the list, but it may take a while until I get around to doing it (lots of other stuff that still needs finishing this year...)

Otherwise - if anyone out there has an interest: since this is mostly about tweaking the export crosswalks a bit, it would make for a great first contribution or pull request. Ping me if you're interested :-)

**Comment by rsimon** [comment]
Will go live with the next update
