### ISSUE TITLE
Is there a way to undo the automatic translation of the workspace? :)

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#628]
This is a dumb question, but my workspace always appears in Italian automatically. I don't know what kind of information it's fetching but I couldn't find a preference setting to get it back to the English. It's a bit confusing when showing others how Recogito works, as people see obscure words in Italian :)

**Comment by rsimon** [comment]
Hi @ChiaraPalladino,

not a dumb question at all - in fact one of these things that have long been on the backlog, and are still waiting to be implemented (if there's ever time...) The language is set based on the pre-configured browser language. I.e. changing the browser setting is one way to get around this. But there's also a "secret hack" which might be easier:

- Log out from Recogito
- Go to the start page, i.e. `recogito.pelagios.org`
- In the browser bar, append a `?lang={code} URL parameter. E.g. to force English

```
http://recogito.pelagios.org?lang=en
```
That will force the UI to English. In order to go back to Italian, either repeat the procedure with "it" as language code; or clear your browser's cookies. (Recogito stores the forced language setting as a cookie.)

The available language codes, BTW, are: bn, de, el, es, fa, fr, he, it, ja, nl, tr. But coverage differs wildly - i.e. for some langauges, only parts of the front page are translated, whereas translation is more comprehensive in other languages.

Cheers,
Rainer

**Comment by rsimon** [comment]
P.S.: the new workspace, BTW, isn't translated yet at all & currently available in English. Will hopefully change in the future, too.

**Comment by ChiaraPalladino** [comment]
Ahh, great!! Thanks Rainer!
