### ISSUE TITLE
Slow response on large documents

### ISSUE THREAD

**Issue by ChiaraPalladino** [pelagios/recogito2#70]
Hope it's not my problem, but on rather large documents it systematically gets very slow, both at the opening and at switching view, sometimes during the annotation stage. It doesn't crash, but it takes about one minute to recover.  

- Edit: it may crash when the amount of annotations increases.

**Comment by rsimon** [comment]
Yes, good point. A known problem, but indeed one that's not yet recorded explicitely as an issue in GitHub. The bottleneck is the client-side rendering of the annotation coloring (i.e. the step where the code manipulates the HTML document structure, surrounding text snippets with highlight elements, one after the other).

It's (almost certainly) not going to go away entirely. But I have several steps of remedy planned for this already. Can you give me a rough indicating of your setup? (Used browser, # of annotations before delays get significant, rough specs of the machine you are using in terms of CPU if you can find it out?)

Below, here's the steps I'm planning - note that this is mostly info to myself for later when I can start working on the issue:

* First step: render annotations in batches, with short breaks in between. This way, rendering will take
  longer, but the UI should remain responsive instead of blocking. (And the user would probably not "feel"
  the rendering unless quickly scrolling down immediately, as annotations are rendered top to bottom.)
* Second step: lazy loading. Rendering of annotations outside the viewport could be delayed
  altogether, until the user actually scrolls down.
* Third step: (feasibilty needs to be clarified) server-side rendering. DOM rendering is notoriously slow 
  (relatively speaking...) in the browser. So this might be something we can pre-generate on the server.
  The old Recogito has done this; but the logic was significantly simpler back then. The only good
  option I see is to find a way where we can execute the same client-side JS on the server.

**Comment by ChiaraPalladino** [comment]
It started delaying immediately after loading the document, and still gets stuck while changing view from Annotation to Map and viceversa, but it almost crashed while I was testing multiple annotations on the same line (e.g. multi-word annotation and then single-word annotation on the same sentence), which figures considering what you're saying. 
I currently have less than 200 annotations on one single document. 

I am now working on a (quite old actually) Windows 7 Professional with Intel Core i5 450M, 2.40 GHz and 8 GB RAM. I generally use Chrome as browser, will try with other options as well.

**Comment by eltonteb** [comment]
I experienced something this back in November when I was working on Strabo. (I think I mentioned it to you then, Rainer.) I would often have to be quite careful about how many annotations I was making in the text before switching to the geo-resolution screen, since otherwise I would lose a whole bunch and have to do them again.

I was working on a MBA (OS Yosemite) and using Chrome.

**Comment by rsimon** [comment]
@ChiaraPalladino thx for the specs. Definitely a state of the art machine, and a small-to-reasonable number of annotations so I'll aim for that as a first test case ;-) (I've also been testing this on my personal Netbook - which seems to do a really good job of representing a slow machine...)

Do you think there's a performance difference when annotations overlap (rather than when there's just a large number of them)? My expectation is that this shouldn't matter too much - but let me know if you getting other results!

A switch from map to text will rebuild the whole page, BTW. Just to explain why a switch isn't faster than the initial load.

**Comment by rsimon** [comment]
Ah @eltonteb... that is, of course, an - almost - totally unrelated issue since the new Recogito works very different in this regard ;-) But I'll test with both Strabo and Pausanias since they are (with ~11k annotations) our "biggest" documents so far.

**Comment by ChiaraPalladino** [comment]
I'd say that there is a difference when annotations overlap. But I need to test this more thoroughly, I don't have many overlaps currently.

**Comment by rsimon** [comment]
Note: also relates to issue #63

**Comment by rsimon** [comment]
@ChiaraPalladino ok, thanks for spotting this - I'll take a look!

**Comment by rsimon** [comment]
Note: option 1 does not work; it still blocks the UI thread unless batch sizes are made unusably small and/or breaks between batches are made usuably long. Looking into lazy loading next.

**Comment by rsimon** [comment]
Option 2 doesn't look too good either. Even if only the visible annotations are rendered, the client still needs to perform parts of the DOM manipulation to evaluate whether an annotation is actually visible. It's still an improvement over option 1. But very likely we'll need to go for Option 3.

**Comment by rsimon** [comment]
Small update: did more research & trialling and it seems certain that any kind of batch/background rendering will __not__ solve the problem, as the UI will always be unresponsive as long as rendering is taking place. 

This means there are, definitely, only two options:

* Make rendering in the browser __much__ faster
* Render on the server

Following a tweet by @grantdelozier, I made some tweaks to our rendering code, plus benchmarked the maximum speed we can get when disallowing overlapping annotations. (I got slightly more than 1sec for ~1.3k annotations.) We'd now need some extra logic that checks, before rendering an annotation, whether we're dealing with overlap or not - and then choose between fast vs. slow rendering accordingly.

Ultimately, we'll IMO want server-side rendering __in addition__ to this approach, to be on the safe side for ultra-big docs and/or docs with lots of overlapping annotations.

**Comment by ChiaraPalladino** [comment]
Works **much** faster now for: switching to map view and multiple annotations. 
However, it now inevitably crashes while rebuilding (or even building) the text annotation view. It takes 0:47 secs to build it (still in a document with about 200 annotations).

**Comment by rsimon** [comment]
I didn't actually deploy those changes yet, so you're likely seeing some "natural variation". The above test, BTW, rendered ~70 annotations almost instantly. There's will still be some extra overhead coming because I need to check annotations for overlap each time (which will slow things down). But I'm pretty confident I'm on the right track now.

I'll announce here when there's something to test - definitely some time in the next days!

**Comment by rsimon** [comment]
Hi Chiara, I deployed a first-phase fix to this. Should speed up initial page load significantly. (You may need to click SHIFT+F5, or SHIFT+browser refresh button to make sure you're not getting the old code from the browser cache.)

I think I may have broken some other things in the process. So updates will follow during the day ;-)

**Comment by rsimon** [comment]
Quick note: performance seems good nie in large docs but completely drops as soon as there's a single overlap. Investigate.

**Comment by rsimon** [comment]
Copying links to the following threads for reference:

https://github.com/timdown/rangy/issues/330
https://github.com/timdown/rangy/issues/376

**Comment by rsimon** [comment]
Hi @ChiaraPalladino, a fix is deployed & ready for testing. Things seem to work significantly faster now, hopefully to the extent that it's usable. (I tested with our biggest documents - Mandeville, Strabo, Pausanias - and up to ~1.350 annotations on a single page.)

There are still two potential additions upcoming (later):
* A visual 'load' indicator that provides feedback that annotations are still being loaded
* A performance optimization which specifically targets the case of switching back and forth
  between text and map inside the same document
